name: Tests
on:
  push:
  pull_request:
  schedule:
    - cron: '38 9 * * *'
  workflow_dispatch:
    inputs:
      snap-tracks:
        description: List of snap tracks to run the tests. In JSON format, i.e. '["latest/stable", "5.0/candidate"]'.
        type: string
        default: '["latest/edge"]'
      self-hosted-runner:
        type: boolean
        description: Whether to use self-hosted runners to run the jobs.
        default: false
      tmate-debug:
        description: Use tmate debugging session on integration test failure.
        type: boolean
        default: false
      tmate-timeout:
        description: Timeout in minutes to keep tmate debugging session.
        type: number
        default: 30

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    # Make sure bash is always invoked with `-eo pipefail`
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsshell
    shell: bash

jobs:
  code-tests:
    name: Code
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # A non-shallow clone is needed for the Differential ShellCheck
          fetch-depth: 0

      - name: yamllint
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: .github/workflows/

      - id: ShellCheck
        name: Differential ShellCheck
        uses: redhat-plumbers-in-action/differential-shellcheck@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          strict-check-on-push: true
        if: github.event_name == 'pull_request'

      - name: Upload artifact with ShellCheck defects in SARIF format
        uses: actions/upload-artifact@v4
        with:
          name: Differential ShellCheck SARIF
          path: ${{ steps.ShellCheck.outputs.sarif }}
        if: github.event_name == 'pull_request'

  system-tests:
    env:
      PURGE_LXD: "1"
    name: ${{ matrix.test }} (${{ matrix.track }})
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        track: ${{ fromJSON(inputs.snap-tracks || '["latest/edge", "5.21/edge", "5.0/edge"]') }}
        test:
          - cgroup
          - cluster
          - container-copy
          - cpu-vm
          - devlxd-vm
          - docker
          - efi-vars-editor-vm
          - interception
          - pylxd
          - network-bridge-firewall
          - network-ovn
          - network-routed
          - storage-buckets
          - storage-disks-vm
          - "storage-vm dir"
          - "storage-vm btrfs"
          - "storage-vm ceph"
          - "storage-vm lvm"
          - "storage-vm lvm-thin"
          - "storage-vm zfs"
          - storage-volumes-vm
          - tpm-vm
          - vm-nesting
        exclude:
          - test: efi-vars-editor-vm # not compatible with 5.0/*
            track: "5.0/edge"
          - test: storage-buckets  # waiting for integration with microceph
          - test: "storage-vm ceph" # waiting for integration with microceph

    steps:
      - name: Performance tuning
        run: |
          set -eux
          # optimize ext4 FSes for performance, not reliability
          for fs in $(findmnt --noheading --type ext4 --list --uniq | awk '{print $1}'); do
            # nombcache and data=writeback cannot be changed on remount
            sudo mount -o remount,noatime,barrier=0,commit=6000 "${fs}" || cat /proc/self/mountinfo
          done

          # disable dpkg from calling sync()
          echo "force-unsafe-io" | sudo tee /etc/dpkg/dpkg.cfg.d/force-unsafe-io

      - name: Reclaim some space (storage tests only)
        if: ${{ startsWith(matrix.test, 'storage') }}
        run: |
          set -eux
          df -h

          sudo snap remove lxd --purge
          # Purge older snap revisions that are disabled/superseded by newer revisions of the same snap
          snap list --all | while read -r name _ rev _ _ notes _; do
            [[ "${notes}" =~ disabled$ ]] && sudo snap remove "${name}" --revision "${rev}" --purge
          done || true

          # This was inspired from https://github.com/easimon/maximize-build-space
          df -h
          # dotnet
          sudo rm -rf /usr/share/dotnet
          # android
          sudo rm -rf /usr/local/lib/android
          # haskell
          sudo rm -rf /opt/ghc
          df -h

      - name: Remove docker
        run: |
          set -eux
          sudo apt-get autopurge -y containerd.io docker-ce podman uidmap
          sudo ip link delete docker0
          sudo nft flush ruleset

      - name: Remove needrestart
        run: |
          # XXX: workaround https://bugs.launchpad.net/ubuntu/+source/needrestart/+bug/2067800
          #      needrestart restarting runner-provisioner.service causes an immediate job failure:
          #
          #Restarting services...
          # /etc/needrestart/restart.d/systemd-manager
          # systemctl restart packagekit.service php8.3-fpm.service runner-provisioner.service systemd-journald.service systemd-networkd.service systemd-resolved.service systemd-udevd.service udisks2.service walinuxagent.service
          #Terminated
          #++ cleanup
          sudo apt-get autopurge -y needrestart

      - name: Checkout
        uses: actions/checkout@v4

      - name: ${{ matrix.test }} (${{ matrix.track }})
        run: |
          set -eux
          TEST_SCRIPT="$(echo ${{ matrix.test }} | cut -d " " -f 1)"
          EXTRA_ARGS="$(echo ${{ matrix.test }} | cut -d " " -f 2- --only-delimited)"
          if [ "${TEST_SCRIPT}" = "cluster" ]; then
            dst_track="${{ matrix.track }}"
            src_track="$(echo "${dst_track}" | cut -d/ -f1)/stable"
            EXTRA_ARGS="${EXTRA_ARGS:-3} ${src_track} ${{ matrix.track }}"
          fi
          sudo --preserve-env=PURGE_LXD,TEST_IMG ./bin/local-run "tests/${TEST_SCRIPT}" ${{ matrix.track }} ${EXTRA_ARGS:-}

      - name: Tmate debugging session (self-hosted)
        if: ${{ failure() && inputs.tmate-debug && inputs.self-hosted-runner }}
        uses: canonical/action-tmate@main
        timeout-minutes: ${{ inputs.tmate-timeout }}
      - name: Tmate debugging session (gh-hosted)
        if: ${{ failure() && inputs.tmate-debug && !inputs.self-hosted-runner }}
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: ${{ inputs.tmate-timeout }}
